### ISSUE TITLE
Create First Alpha Release

### ISSUE THREAD

**Issue by rlove** [utPLSQL/utPLSQL#116]
This issue is to move version 3 out of the shadows and in prime time with its first public alpha release.

Resolve Blocking issues:
- [x] Automate Deployment by Tagging Release - #95
- [ ] Publish documentation on merge with version3 branch  #59 (Realized this was not blocking so will do seperately.
- [x] Travis-CI automation of release #70

Tasks to complete (Guess on GIT steps may find a better way to move Version3 to master )
- [x] Create new temporary fork of repository.  (Backup)
- [x] Local Repo - Create a version2 from last master branch.
- [x] Local Repo - Delete Master Branch
- [x] Local Repo - Create Master Branch from Version3 branch.
- [x] Local Repo - Delete Version3 Branch
- [x] utPLSQL/utPLSQL - Push version2 branch
- [x] utPLSQL/utPLSQL - Force Push master branch
- [x] utPLSQL/utPLSQL - Delete version3 branch
- [x] Update GitHub Branch permissions.
- [x] Update readme.md with a reference to version 2.
- [x] Make Blog post on https://utplsql.github.io 
- [x] Make Twitter Announcement

**Comment by Pazus** [comment]
How is it going?

**Comment by jgebal** [comment]
@rlove I'd like to suggest a bit different, maybe easier approach to repo reorganizing.
* **master** - contains most recent official release.
* **develop** - contains most up to date version (under development)

Maybe we should create a develop branch and simply merge version3 into it.
We could then delete version 3 branch without no issues.
We could make develop as the default branch for the repo, so that anyone entering github project can see the most recent progress immediately.
Additionally, we could use tags for marking _alpha_, _release candidate_ and _release_ versions.
Every release stable version should be merged to master.

What do you think?

**Comment by Pazus** [comment]
I think the separate branch for v2 is needed.
I agree that we'll come up with master/develop combination, but master is going to reference to v3 variant.

**Comment by Pazus** [comment]
How is it going, @rlove ?

**Comment by rlove** [comment]
This was completed last night.
