### ISSUE TITLE
Epic - improvements of ut_data_value_refcursor

### ISSUE THREAD

**Issue by jgebal** [utPLSQL/utPLSQL#448]
Following requirements need to be met by ut_data_value_refcursor:
- [ ] ability to extract cursor definition information, in particular column names and data types
- [ ] ability to compare cursor definition before comparing cursor data, so that comparison can fail faster and with better information
- [ ] ability to join cursors by specific columns (PK/UK). Currently cursors are compared as sorted lists of rows (by row position)
- [ ] ability to report only the rows that are different (side by side). Currently we simply display first 100 rows of both cursors.
- [ ] ability to report count of rows in cursor as well as count of differences, so that if there is large number of differences and we don't display all of them, we still report the statistics.

**Comment by jgebal** [comment]
## Ability to extract cursor definition information
------------

When consructing `ut_data_value_refcursor`, we need to capture the cursor number using `dbm_sql.to_cursor_number` and store it as attribute of the object.
New type `ut_data_value_cursor_def` needs to be created to store description of cursor definition (column names and data types). 

Descriptor would be the attribute of `ut_data_value_refcursor`.

**Comment by jgebal** [comment]
## Ability to compare cursor definition before comparing cursor data
---------------------
The type `ut_data_value_cursor_def` should implement a comparator method `compare_implementaion` to allow comparison between descriptors.
The type needs to have `to_string` and a `diff` function, so that we can build a report that would contain:
- full descriptor of cursor
- diff of descriptors of tow cursors

Diff might be a challenge as it's hard to present a meaningful diff in a plain text format.

**Comment by jgebal** [comment]
## Ability to join cursors by specific columns(PK/UK)
---------------------------

This feature could/should be implemented in a similar fashion as excluding columns with `a_exclude` parameter.

We would have additional parameter for the `ut_equal` matcher if the matcher is used with refcursor.

If the parameter is present, we can transform it into XPATH to extract PK/UK/join specific column values from the data and store them in a separate VARCHAR2 column of the temp table for cursor data (with limit of 4000 bytes).
There are few ways of extracting column data from XML - XSL
https://stackoverflow.com/questions/17314062/how-to-convert-xml-to-csv-using-xsl
or 
Extract with XPath:
```
select extract(dbms_xmlgen.getxmltype('
       select object_name, object_type
       from user_objects
       '),'//OBJECT_NAME/text()|//OBJECT_TYPE/text()') xml
from dual;
```

The temp table keys column could be indexed with a unique index, so that we can actually validate that the join columns are unique.

If columns are not unique, the expectation should fail with meaningful message informing that the cursor data contains duplicates. 
We need to be able to inform the user which of the compared cursors doesn't have uniqueness which is again tricky as the data_value are not aware of where they were created from (actual or expected).

**Comment by jgebal** [comment]
## Ability to report only the rows that are different
---------------------
Currently we simply display first N rows form both cursors if the data is not matching.

This is not very useful for developers, specially when dealing with more than few columns and few rows of data.

`ut_data_value_refcursor` should implement some kind of diff report, that would:
- only report on rows that are actually different
- display mismatching rows side by side or one under another so we can see one expected row, one actual etc.

As an idea, when running the `compare_implementation` method, we could save the results (or data-keys) of both compared cursors into separate diff table so that we can then simply query diff table joined with cursor data table (twice) to get differences and the diff data.

It would be worth doing a bit of research on was to do Diff.
There is a nice open-source algorithm for text-based diff:
https://neil.fraser.name/software/diff_match_patch/svn/trunk/demos/demo_diff.html
https://github.com/curran/google-diff-match-patch

RSpec and git command line have a line by line diff implementation too, that could be more suitable here.

**Comment by jgebal** [comment]
## Ability to report count of rows in cursor as well as count of differences
---------------------
If an expectation fails and we have large data-set, there is no point in displaying all differences, specially if there is more than 5-10-50? diffing rows.

We definitely should provide additional information in that case:
Something like:
```
  Data diff truncated, showing 5 out of X differences.
  Expected rows = A
  Actual rows = B
```

**Comment by jgebal** [comment]
Closing - split into smaller issues
